name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v0.1.4

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          pyinstaller --windowed --onedir --name Timebox timebox.py
        else
          pyinstaller --onefile --windowed --name Timebox timebox.py
        fi
      shell: bash

    - name: Package & Checksum (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        mkdir -p dist/${{ runner.os }}
        cp -R dist/Timebox* dist/${{ runner.os }}/
        cd dist
        zip -r Timebox-${{ runner.os }}.zip ${{ runner.os }}
        shasum -a 256 Timebox-${{ runner.os }}.zip > checksums-${{ runner.os }}.txt

    - name: Package & Checksum (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        New-Item -ItemType Directory -Force -Path dist\Windows
        Copy-Item dist\Timebox.exe dist\Windows\
        Compress-Archive -Path dist\Windows\* -DestinationPath dist\Timebox-Windows.zip
        certutil -hashfile dist\Timebox-Windows.zip SHA256 | Out-File -Encoding ascii dist\checksums-Windows.txt

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        files: |
          dist/Timebox-*.zip
          dist/checksums-*.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
