name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "Timebox" timebox.py

    - name: Generate SHA256 Checksum
      run: |
        cd dist
        if [ -f Timebox ]; then
          shasum -a 256 Timebox > checksums.txt
        elif [ -f Timebox.exe ]; then
          certutil -hashfile Timebox.exe SHA256 > checksums.txt
        elif [ -d Timebox.app ]; then
          zip -r Timebox-macos.zip Timebox.app
          shasum -a 256 Timebox-macos.zip > checksums.txt
        fi

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        name: "Release ${{ github.ref_name }}"
        tag_name: "${{ github.ref_name }}"
        files: |
          dist/Timebox*
          dist/checksums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
