name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "Timebox" timebox.py

    - name: Generate SHA256 Checksum
      run: |
        cd dist
        shasum -a 256 timebox* > checksums.txt || certutil -hashfile timebox.exe SHA256 > checksums.txt || openssl dgst -sha256 timebox > checksums.txt

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        name: "Release ${{ github.sha }}"
        tag_name: "${{ github.sha }}"
        files: |
          dist/timebox*
          dist/checksums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
